### ISSUE TITLE
error: could not convert ‘file’ from ‘filekey’ to ‘std::string {aka std::basic_string<char>}’

### ISSUE THREAD

**Issue by JCodeMan** [choury/baidudisk#2]
When i run 'make' command, it give me an error message like title. Could you look up  what the wrong is?
当我执行cmake通过后，再执行make的时候，会有如标题上的错误。请问是哪里的问题？

Detail error messsage in below:
`
[root@xstar baidudisk]# make
[  5%] Building CXX object fmdisk/src/CMakeFiles/fmcheck.dir/check.cpp.o
/root/code/baidudisk/fmdisk/src/check.cpp: In function ‘filekey* getpath(std::string)’:
/root/code/baidudisk/fmdisk/src/check.cpp:256:32: error: could not convert ‘file’ from ‘filekey’ to ‘std::string {aka std::basic_string<char>}’
         return new filekey{file};
                                ^
make[2]: *** [fmdisk/src/CMakeFiles/fmcheck.dir/check.cpp.o] Error 1
make[1]: *** [fmdisk/src/CMakeFiles/fmcheck.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by choury** [comment]
Please provide your environment. 
distro and gcc version

**Comment by JCodeMan** [comment]
```
# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC）
```

**No distro installed in my centos7 os. Is itnecessary for the project compiled? If yes ,does it mean the below github link?**
[torch/distro](https://github.com/torch/distro)

**Comment by choury** [comment]
Centos7 is your distro.
This issue was confirmed, and will be fixed soon.
